VITE_SUPABASE_URL=https://eaxvvhamkmovkoqssahj.supabase.co
VITE_SUPABASE_FUNCTIONS_URL=https://eaxvvhamkmovkoqssahj.supabase.co/functions/v1
VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVheHZ2aGFta21vdmtvcXNzYWhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4MzE2NzMsImV4cCI6MjA3NzQwNzY3M30.HZMdHCOTxDidFwWJezlvFXRr8qlZedfyOJ55o3H4zvw
