// Regra de raciocinio compartilhada entre a geracao e os refinamentos de
// follow-up. Ela nao classifica a conversa no backend nem cria um segundo
// fluxo: preserva a leitura completa do modelo, mas impede que a ordem
// cronologica esconda uma decisao comercial que continua aberta.
export const COMMERCIAL_THREAD_RULE = [
  'FIO COMERCIAL PENDENTE — DISTINGA A ULTIMA MENSAGEM DO CHAT DO ULTIMO EVENTO COMERCIAL RELEVANTE. A ultima mensagem cronologica nao e automaticamente o ponto em que a venda parou.',
  'Antes de escrever, reconstrua internamente o ultimo fio comercial ainda nao resolvido: qual assunto/produto estava em decisao, qual foi a ultima microdecisao solicitada ou combinada, quem ficou responsavel pela proxima acao, se o cliente assumiu compromisso explicito, se o compromisso foi executado e qual posicionamento concreto falta obter agora.',
  'Procure tambem terceiro decisor: quando o cliente disser que vai falar, mostrar ou apresentar algo para esposa, marido, socio, mae ou outra pessoa, reconheca quem participaria da decisao, o que essa pessoa deveria avaliar e qual escolha ficou pendente. Se nao houver resposta posterior que resolva a decisao, retome esse contexto especifico e busque um posicionamento facil de responder — nao reduza a conversa a um check-in generico.',
  'Mensagens posteriores sobre assuntos paralelos — pessoais, juridicos, administrativos, de pos-venda ou outro tema sem relacao com a nova contratacao — nao apagam uma pendencia comercial anterior. Se uma decisao, objecao, compromisso ou acao comercial ficou explicitamente em aberto e depois a conversa migrou para outro tema, reconstrua o ultimo fio comercial nao resolvido antes de gerar o follow-up.',
  'Quando existir microdecisao ou compromisso comercial explicito ainda nao resolvido, NAO o substitua por frases vazias como "Conseguiu avaliar?", "Conseguiu olhar?", "Viu as opcoes?", "Ficou alguma duvida?", "Ainda tem interesse?", "Qualquer duvida estou a disposicao" ou "Se precisar de algo pode me chamar". Use as alternativas, condicoes, objecao, acao ou decisor reais que constam no historico e peca a proxima decisao concreta.',
  'Nao invente um fio pendente: se o cliente deixou claro que contratou outra opcao, decidiu nao seguir, encerrou a oportunidade ou resolveu explicitamente a decisao, trate o fio como resolvido conforme o historico e as regras atuais.',
  'Esta regra nao supera o CONTEXTO HUMANO E EMPATIA. Em luto, doenca, cirurgia, internacao ou outra situacao sensivel, a abordagem humana e a recomendacao de esperar podem ser mais adequadas do que retomar uma venda tecnicamente pendente.',
  'A regra de NAO REPETIR ESTRATEGIA continua valendo: se ja houve follow-up sobre a mesma decisao sem resposta, nao repita a pergunta ao decisor com sinonimos. Mude a funcao comercial conforme o historico, por exemplo simplificando a escolha, investigando o bloqueio, pedindo posicionamento sobre continuidade ou recomendando pausa.',
].join('\n');
