import type { OperatorLandingContent } from './types';

const commonContractProfiles = [
  {
    label: 'Pessoa física e família',
    detail: 'A Kifer confirma as opções elegíveis para sua cidade e faixa etária.',
  },
  {
    label: 'MEI, PME e empresarial',
    detail: 'A análise considera CNPJ, número de vidas e a regra comercial vigente.',
  },
] as const;

const commonCommercialNotes = [
  'Preço, carência, coparticipação e elegibilidade dependem do produto e da análise do perfil.',
  'A disponibilidade de rede deve ser conferida para a cidade e os locais de atendimento mais importantes para você.',
  'A Kifer Saúde apresenta as condições válidas antes do envio de qualquer proposta.',
] as const;

const createOperator = (content: Omit<OperatorLandingContent, 'contractProfiles' | 'commercialNotes' | 'path'>): OperatorLandingContent => ({
  ...content,
  path: `/planos/${content.slug}`,
  contractProfiles: commonContractProfiles,
  commercialNotes: commonCommercialNotes,
});

export const operatorLandingPages: readonly OperatorLandingContent[] = [
  createOperator({
    name: 'Amil',
    slug: 'amil',
    logoPath: '/amil-logo-1-2.png',
    logoAlt: 'Logo Amil',
    accentTone: 'info',
    eyebrow: 'Planos Amil com orientação da Kifer Saúde',
    heroHeadline: 'Encontre uma opção Amil coerente com a sua rotina.',
    heroDescription: 'Compare as possibilidades da Amil com apoio consultivo para entender cobertura, rede, contratação e próximos passos.',
    valueProposition: 'A Kifer organiza a conversa para você olhar além do preço e decidir com clareza o que precisa ser confirmado antes da contratação.',
    minimumLives: 'Confirmado conforme o produto e o tipo de contratação.',
    coverage: 'Consultada por cidade, região de uso e rede de atendimento desejada.',
    products: ['Linhas e categorias disponíveis no momento da cotação', 'Opções para diferentes perfis de contratação', 'Análise de rede, carência e coparticipação'],
    networkHighlights: ['Hospitais e laboratórios relevantes para sua rotina', 'Disponibilidade por município e produto', 'Conferência consultiva antes da proposta'],
    differentials: ['Comparação orientada pela sua necessidade', 'Explicação simples das regras comerciais', 'Acompanhamento da cotação à ativação'],
    faqs: [
      { question: 'A Amil atende minha cidade?', answer: 'A disponibilidade depende do produto e da área de cobertura. Informe sua cidade para a Kifer consultar a rede aplicável ao seu perfil.' },
      { question: 'Posso contratar como MEI ou empresa?', answer: 'A Kifer verifica a elegibilidade conforme CNPJ, quantidade de vidas e regra comercial vigente antes de apresentar as opções.' },
      { question: 'A cotação já mostra carência e coparticipação?', answer: 'Sim. Esses pontos entram na comparação para que você receba uma orientação clara antes de decidir.' },
    ],
    seo: { title: 'Plano Amil no Rio de Janeiro', description: 'Compare opções de plano Amil no Rio de Janeiro com a orientação consultiva da Kifer Saúde.' },
  }),
  createOperator({
    name: 'Porto Saúde',
    slug: 'porto-saude',
    logoPath: '/porto-logo.png',
    logoAlt: 'Logo Porto Saúde',
    accentTone: 'gold',
    eyebrow: 'Planos Porto Saúde com atendimento da Kifer',
    heroHeadline: 'Conheça as possibilidades da Porto Saúde para o seu perfil.',
    heroDescription: 'A Kifer compara a oferta disponível e traduz as regras da Porto Saúde para uma decisão mais segura e sem pressa.',
    valueProposition: 'Você recebe uma leitura consultiva de custo, rede e elegibilidade antes de avançar para a contratação.',
    minimumLives: 'Confirmado conforme a linha e a modalidade escolhida.',
    coverage: 'Avaliada por região, cidade e locais de atendimento que você realmente utiliza.',
    products: ['Linhas Porto Saúde elegíveis para o seu cenário', 'Alternativas para pessoa, família ou empresa', 'Comparação de rede e condições comerciais'],
    networkHighlights: ['Rede relevante para o seu endereço', 'Hospitais, clínicas e laboratórios a confirmar', 'Orientação sobre abrangência da opção escolhida'],
    differentials: ['Atendimento direto com a corretora', 'Cotação organizada por prioridade', 'Suporte durante documentação e ativação'],
    faqs: [
      { question: 'Como saber qual linha Porto Saúde faz sentido?', answer: 'A Kifer cruza seu orçamento, cidade, rede desejada e perfil de contratação para apresentar apenas opções coerentes para análise.' },
      { question: 'A rede é igual em todas as opções?', answer: 'Não necessariamente. A rede e a abrangência variam por produto e devem ser confirmadas antes da proposta.' },
      { question: 'Posso pedir uma comparação com outra operadora?', answer: 'Sim. A Kifer trabalha com comparação consultiva para ajudar você a enxergar diferenças relevantes entre as opções disponíveis.' },
    ],
    seo: { title: 'Plano Porto Saúde no Rio de Janeiro', description: 'Entenda e compare opções Porto Saúde no Rio de Janeiro com a Kifer Saúde.' },
  }),
  createOperator({
    name: 'Bradesco Saúde',
    slug: 'bradesco-saude',
    logoPath: '/bradesco-saude-logo-1-1.png',
    logoAlt: 'Logo Bradesco Saúde',
    accentTone: 'copper',
    eyebrow: 'Bradesco Saúde apresentado pela Kifer',
    heroHeadline: 'Uma comparação clara para escolher Bradesco Saúde.',
    heroDescription: 'Veja as possibilidades de contratação e peça uma análise feita para sua cidade, quantidade de vidas e prioridades de atendimento.',
    valueProposition: 'A corretora ajuda a colocar rede, custo e regras na mesma conversa, para evitar uma escolha baseada apenas em uma mensalidade inicial.',
    minimumLives: 'Confirmado conforme a modalidade e a regra vigente.',
    coverage: 'Consultada conforme abrangência do produto e região de utilização.',
    products: ['Categorias disponíveis conforme perfil e elegibilidade', 'Possibilidades para PME e empresarial', 'Leitura de coparticipação e carências'],
    networkHighlights: ['Rede hospitalar de interesse do cliente', 'Abrangência e utilização por região', 'Validação da rede antes da decisão'],
    differentials: ['Orientação sem linguagem de operadora', 'Comparativo com alternativas quando fizer sentido', 'Acompanhamento no pós-venda'],
    faqs: [
      { question: 'A Bradesco Saúde tem opção para minha empresa?', answer: 'A Kifer verifica o CNPJ, o número de vidas e a regra comercial vigente para informar quais modalidades podem ser analisadas.' },
      { question: 'Vocês confirmam os hospitais antes da contratação?', answer: 'Sim. A rede relevante para sua rotina é um dos pontos verificados na cotação e na comparação.' },
      { question: 'Existe uma opção ideal para todo mundo?', answer: 'Não. A escolha depende de cidade, orçamento, faixa etária, rede e forma de contratação.' },
    ],
    seo: { title: 'Plano Bradesco Saúde no Rio de Janeiro', description: 'Compare opções Bradesco Saúde com atendimento consultivo da Kifer Saúde no Rio de Janeiro.' },
  }),
  createOperator({
    name: 'SulAmérica',
    slug: 'sulamerica',
    logoPath: '/sulamerica-saude-logo.png',
    logoAlt: 'Logo SulAmérica Saúde',
    accentTone: 'success',
    eyebrow: 'SulAmérica Saúde com curadoria da Kifer',
    heroHeadline: 'Escolha SulAmérica com mais contexto e menos dúvida.',
    heroDescription: 'A Kifer ajuda você a entender as linhas disponíveis, a cobertura e os critérios que mudam de acordo com o perfil.',
    valueProposition: 'A decisão fica mais simples quando as condições comerciais e o uso real da rede aparecem lado a lado.',
    minimumLives: 'Confirmado conforme a linha e o perfil de contratação.',
    coverage: 'Analisada por município, abrangência e locais de atendimento prioritários.',
    products: ['Linhas elegíveis para pessoa, família ou empresa', 'Alternativas de cobertura e rede', 'Comparação de regras antes da proposta'],
    networkHighlights: ['Rede que atende sua região', 'Checagem de prestadores prioritários', 'Atenção para diferenças entre produtos'],
    differentials: ['Cotação com linguagem direta', 'Apoio para comparar cenários', 'Suporte até a ativação do plano'],
    faqs: [
      { question: 'Posso escolher a rede que quero usar?', answer: 'Você pode informar os hospitais, clínicas ou laboratórios prioritários. A Kifer usa esses dados para orientar a comparação da rede disponível.' },
      { question: 'A SulAmérica serve para contratação empresarial?', answer: 'A disponibilidade depende da regra vigente, do CNPJ e do número de vidas. A análise é feita antes de qualquer proposta.' },
      { question: 'A Kifer vende diretamente o plano?', answer: 'A Kifer Saúde é a corretora responsável pelo atendimento e apresenta produtos da operadora, acompanhando você no processo.' },
    ],
    seo: { title: 'Plano SulAmérica no Rio de Janeiro', description: 'Encontre opções SulAmérica no Rio de Janeiro com comparação consultiva da Kifer Saúde.' },
  }),
  createOperator({
    name: 'Unimed FERJ',
    slug: 'unimed',
    logoPath: null,
    logoAlt: 'Unimed FERJ',
    accentTone: 'success',
    eyebrow: 'Unimed FERJ apresentada pela Kifer Saúde',
    heroHeadline: 'Entenda as opções Unimed para a sua região.',
    heroDescription: 'Conte o que você precisa e receba uma orientação da Kifer sobre disponibilidade, abrangência e forma de contratação.',
    valueProposition: 'A rede regional importa. Por isso, a análise parte da cidade e dos locais onde você realmente pretende ser atendido.',
    minimumLives: 'Confirmado conforme o produto e a regra comercial da região.',
    coverage: 'Verificada por município, abrangência e rede local disponível.',
    products: ['Opções regionais conforme área de atuação', 'Categorias para diferentes perfis', 'Comparação de rede e condições'],
    networkHighlights: ['Prestadores relevantes para sua região', 'Abrangência local ou regional a confirmar', 'Consulta de rede antes da proposta'],
    differentials: ['Leitura local da necessidade', 'Comparação sem excesso de jargão', 'Acompanhamento humano do processo'],
    faqs: [
      { question: 'Qual Unimed atende a minha cidade?', answer: 'A Kifer confirma a área de atendimento e a rede aplicável ao seu município antes de orientar a escolha.' },
      { question: 'A Unimed FERJ é um único produto?', answer: 'Existem diferentes linhas e regras comerciais. A página organiza a conversa; a cotação confirma a alternativa disponível para seu perfil.' },
      { question: 'A rede regional é considerada na cotação?', answer: 'Sim. A cidade e os locais de atendimento desejados são informações essenciais para a análise.' },
    ],
    seo: { title: 'Plano Unimed FERJ no Rio de Janeiro', description: 'Conheça opções Unimed FERJ e peça uma cotação consultiva com a Kifer Saúde.' },
  }),
  createOperator({
    name: 'MedSênior',
    slug: 'medsenior',
    logoPath: null,
    logoAlt: 'MedSênior',
    accentTone: 'gold',
    eyebrow: 'MedSênior com orientação da Kifer Saúde',
    heroHeadline: 'Uma conversa cuidadosa para avaliar MedSênior.',
    heroDescription: 'A Kifer entende o perfil da família, a região e as prioridades de atendimento antes de apresentar as opções disponíveis.',
    valueProposition: 'A contratação de um plano de saúde pede clareza sobre rede, regras, abrangência e adequação ao momento de vida.',
    minimumLives: 'Confirmado conforme o produto e os critérios de elegibilidade.',
    coverage: 'Consultada para a cidade e os pontos de atendimento de interesse.',
    products: ['Linhas disponíveis para o perfil informado', 'Opções de cobertura a confirmar na cotação', 'Orientação sobre regras e utilização'],
    networkHighlights: ['Rede próxima da rotina da família', 'Hospitais, clínicas e laboratórios a confirmar', 'Checagem antes da decisão'],
    differentials: ['Atendimento paciente e sem pressão', 'Explicação das condições comerciais', 'Acompanhamento até a ativação'],
    faqs: [
      { question: 'Como a Kifer avalia se MedSênior faz sentido?', answer: 'A conversa considera cidade, faixa etária, rotina de atendimento, orçamento e a rede que precisa estar disponível.' },
      { question: 'As condições mudam conforme a cidade?', answer: 'Podem mudar. A área de cobertura e a rede devem ser conferidas para o município e o produto escolhidos.' },
      { question: 'A página substitui a proposta comercial?', answer: 'Não. Ela organiza a decisão. A Kifer confirma as condições válidas e apresenta a proposta adequada ao perfil.' },
    ],
    seo: { title: 'Plano MedSênior no Rio de Janeiro', description: 'Avalie opções MedSênior com atendimento consultivo e suporte da Kifer Saúde.' },
  }),
  createOperator({
    name: 'Assim Saúde',
    slug: 'assim-saude',
    logoPath: '/assim-saude-logo.png',
    logoAlt: 'Logo Assim Saúde',
    accentTone: 'terracotta',
    eyebrow: 'Assim Saúde com atendimento Kifer',
    heroHeadline: 'Compare Assim Saúde de um jeito mais simples.',
    heroDescription: 'A Kifer ajuda você a avaliar cobertura, rede, custo e regras de contratação de acordo com o seu momento.',
    valueProposition: 'A escolha parte do que é importante para sua família ou empresa, com confirmação das condições antes de avançar.',
    minimumLives: 'Confirmado conforme produto, modalidade e perfil.',
    coverage: 'Verificada por município, abrangência e rede de utilização.',
    products: ['Alternativas disponíveis para o seu perfil', 'Possibilidades individuais, familiares ou empresariais', 'Comparação de carência e coparticipação'],
    networkHighlights: ['Rede da sua região', 'Prestadores que você quer manter por perto', 'Conferência de cobertura aplicável'],
    differentials: ['Comparação conduzida pela corretora', 'Informação comercial em linguagem clara', 'Suporte no processo de contratação'],
    faqs: [
      { question: 'A Assim Saúde tem opções para toda a família?', answer: 'A Kifer verifica as opções disponíveis para a composição familiar, idades e cidade informadas na cotação.' },
      { question: 'Posso contratar com CNPJ?', answer: 'A possibilidade depende da regra comercial, do CNPJ e do número de vidas. A elegibilidade é confirmada na análise.' },
      { question: 'Vocês ajudam depois que eu contrato?', answer: 'Sim. A Kifer acompanha a documentação, a ativação e as dúvidas do processo de contratação.' },
    ],
    seo: { title: 'Plano Assim Saúde no Rio de Janeiro', description: 'Compare opções Assim Saúde no Rio de Janeiro com a orientação da Kifer Saúde.' },
  }),
  createOperator({
    name: 'Hapvida / NotreDame Intermédica',
    slug: 'hapvida-notredame',
    logoPath: null,
    logoAlt: 'Hapvida e NotreDame Intermédica',
    accentTone: 'info',
    eyebrow: 'Hapvida e NotreDame Intermédica com a Kifer',
    heroHeadline: 'Veja se as opções Hapvida ou NotreDame combinam com você.',
    heroDescription: 'A Kifer compara a disponibilidade regional e explica os pontos que precisam ser confirmados para o seu perfil.',
    valueProposition: 'Quando a rede própria e a abrangência são decisivas, uma conversa sobre localização e rotina evita escolhas desalinhadas.',
    minimumLives: 'Confirmado conforme a linha, a região e a modalidade.',
    coverage: 'Analisada por cidade, área de atendimento e rede disponível.',
    products: ['Linhas e categorias a confirmar na cotação', 'Possibilidades para diferentes perfis', 'Leitura de cobertura e regras comerciais'],
    networkHighlights: ['Rede disponível na sua região', 'Pontos de atendimento prioritários', 'Confirmação da abrangência antes da proposta'],
    differentials: ['Orientação regional', 'Comparação de cenários possíveis', 'Atendimento até a ativação'],
    faqs: [
      { question: 'Hapvida e NotreDame Intermédica são a mesma opção?', answer: 'A apresentação comercial depende da região e do produto. A Kifer esclarece qual opção está disponível para o perfil informado.' },
      { question: 'A rede própria atende minha cidade?', answer: 'A área e a rede variam conforme o produto. Informe a cidade para uma conferência antes da proposta.' },
      { question: 'Existe contratação para empresa?', answer: 'A Kifer verifica as modalidades empresariais conforme CNPJ, número de vidas e regras comerciais vigentes.' },
    ],
    seo: { title: 'Plano Hapvida e NotreDame no Rio de Janeiro', description: 'Entenda as opções Hapvida e NotreDame Intermédica com a Kifer Saúde.' },
  }),
  createOperator({
    name: 'Leve Saúde',
    slug: 'leve-saude',
    logoPath: null,
    logoAlt: 'Leve Saúde',
    accentTone: 'terracotta',
    eyebrow: 'Leve Saúde apresentada pela Kifer',
    heroHeadline: 'Uma opção Leve Saúde pode caber melhor no seu cenário.',
    heroDescription: 'A Kifer ajuda você a entender disponibilidade, rede e regras antes de comparar a alternativa com outras opções.',
    valueProposition: 'O melhor caminho é enxergar o que o produto entrega para sua rotina e o que precisa ser validado antes de contratar.',
    minimumLives: 'Confirmado conforme modalidade e produto disponível.',
    coverage: 'Consultada para sua cidade e região de uso.',
    products: ['Opções disponíveis para o perfil da cotação', 'Análise de cobertura e rede', 'Comparação com alternativas quando fizer sentido'],
    networkHighlights: ['Atendimento perto dos seus deslocamentos', 'Rede e abrangência a confirmar', 'Conferência dos locais prioritários'],
    differentials: ['Conversa direta e sem pressão', 'Critérios de comparação explicados', 'Acompanhamento comercial completo'],
    faqs: [
      { question: 'A Leve Saúde está disponível para minha cidade?', answer: 'A Kifer confirma a disponibilidade por região e produto a partir dos dados da sua cotação.' },
      { question: 'A mensalidade é o único critério?', answer: 'Não. A análise também considera rede, abrangência, carência, coparticipação e o perfil de contratação.' },
      { question: 'Como começo uma cotação?', answer: 'Preencha o formulário da Kifer ou fale pelo WhatsApp. A equipe retorna com os próximos passos para o seu caso.' },
    ],
    seo: { title: 'Plano Leve Saúde no Rio de Janeiro', description: 'Conheça e compare opções Leve Saúde com a Kifer Saúde.' },
  }),
  createOperator({
    name: 'Klini',
    slug: 'klini',
    logoPath: null,
    logoAlt: 'Klini',
    accentTone: 'copper',
    eyebrow: 'Klini com orientação consultiva da Kifer',
    heroHeadline: 'Avalie Klini com uma comparação feita para a sua realidade.',
    heroDescription: 'Conte sua cidade, perfil e prioridade de atendimento para a Kifer confirmar as opções e regras aplicáveis.',
    valueProposition: 'A corretora organiza os detalhes essenciais para você entender se a opção faz sentido antes de receber uma proposta.',
    minimumLives: 'Confirmado conforme produto e modalidade elegível.',
    coverage: 'Verificada por município, abrangência e locais de utilização.',
    products: ['Linhas disponíveis conforme análise do perfil', 'Possibilidades individuais ou empresariais a confirmar', 'Comparação de condições comerciais'],
    networkHighlights: ['Rede relevante para o seu dia a dia', 'Área de cobertura a confirmar', 'Checagem antes da contratação'],
    differentials: ['Curadoria da Kifer Saúde', 'Informação objetiva sobre regras', 'Suporte até o pós-venda'],
    faqs: [
      { question: 'O que preciso informar para cotar Klini?', answer: 'Cidade, idade ou faixas etárias, quantidade de vidas e tipo de contratação ajudam a Kifer a iniciar a análise.' },
      { question: 'A cobertura varia por produto?', answer: 'Sim. A cobertura, a rede e as condições comerciais são confirmadas para a opção disponível no seu perfil.' },
      { question: 'Posso comparar Klini com outras operadoras?', answer: 'Sim. Quando houver alternativas coerentes, a Kifer pode apresentar diferenças para apoiar sua decisão.' },
    ],
    seo: { title: 'Plano Klini no Rio de Janeiro', description: 'Peça uma cotação Klini com orientação consultiva da Kifer Saúde.' },
  }),
] as const;
